mrsport_user:
    resource: "@MrsportBundle/Resources/config/routing/user.yml"
    prefix:   /user
mrsport_club:
    resource: "@MrsportBundle/Resources/config/routing/club.yml"
    prefix:   /club
mrsport_evenements:
    resource: "@MrsportBundle/Resources/config/routing/evenements.yml"
    prefix:   /evenements
mrsport_sports:
    resource: "@MrsportBundle/Resources/config/routing/sports.yml"
    prefix:   /sports

mrsport_homepage:
    path:     /
    defaults: { _controller: MrsportBundle:Default:index }

mrsport_backoffice:
    path:     /backoffice
    defaults: { _controller: MrsportBundle:Default:back_office }

mrsport_resultatbasket:
    path:     /resultatbasket
    defaults: { _controller: MrsportBundle:Default:basket_resultat_classement }

mrsport_agendabasket:
    path:     /agendabasket
    defaults: { _controller: MrsportBundle:Default:basket_agenda }

mrsport_basket:
    path:     /basket
    defaults: { _controller: MrsportBundle:Default:basket }

mrsport_football:
    path:     /football
    defaults: { _controller: MrsportBundle:Default:football }

mrsport_agendafootball:
    path:     /agendafootball
    defaults: { _controller: MrsportBundle:Default:football_agenda }

mrsport_resultatfootball:
    path:     /resultatfootball
    defaults: { _controller: MrsportBundle:Default:football_resultat_classement }

mrsport_listeclub:
    path:     /listeclub
    defaults: { _controller: MrsportBundle:Default:liste_club }

mrsport_singleclub:
    path:     /singleclub
    defaults: { _controller: MrsportBundle:Default:single_club }

mrsport_contact:
    path:     /contact
    defaults: { _controller: MrsportBundle:Default:contact }

mrsport_agendahockey:
    path:     /agendahockey
    defaults: { _controller: MrsportBundle:Default:hockey_agenda }

mrsport_resultathockey:
    path:     /resultathockey
    defaults: { _controller: MrsportBundle:Default:hockey_resultat_classement }
 
mrsport_hockey:
    path:     /hockey
    defaults: { _controller: MrsportBundle:Default:hockey }

mrsport_rugby:
    path:     rugby
    defaults: { _controller: MrsportBundle:Default:rugby }

mrsport_resultatrugby:
    path:     /resultatrugby
    defaults: { _controller: MrsportBundle:Default:rugby_resultat_classement }  

mrsport_agendarugby:
    path:     /agendarugby
    defaults: { _controller: MrsportBundle:Default:rugby_agenda } 

mrsport_evenement:
    path:     /evenement
    defaults: { _controller: MrsportBundle:Default:evenement }

mrsport_dashboard:
    path:     /admin/
    defaults: { _controller: MrsportBundle:Default:dashboard }

mrsport_validation_club:
    path:     /admin/validation_club
    defaults: { _controller: MrsportBundle:Club:adminClub }

mrsport_validation_evenement:
    path:     /admin/validation_evenement
    defaults: { _controller: MrsportBundle:Evenements:adminEvenements }

mrsport_listing_users:
    path:     /admin/listing_users
    defaults: { _controller: MrsportBundle:User:adminUser }



