<?php

namespace MrsportBundle\Repository;

/**
 * evenementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evenementsRepository extends \Doctrine\ORM\EntityRepository
{

    public function findlastfive()
    {

        $qb = $this->createQueryBuilder('e')
                    ->orderBy('e.id', 'DESC')
                    ->getQuery()->setMaxResults(5);

            return $qb->execute();
    }

    public function getEventWithStatus($status = 'valide')
    {

        $qb = $this->createQueryBuilder('e')
                ->where("e.status = :identifier")
                ->orderBy('e.date', 'ASC')
                ->setParameter(':identifier', $status)
                ->getQuery();
                   
            return $qb->execute();
    }
  
    
}
