<?php

namespace MrsportBundle\Repository;

/**
 * sportsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sportsRepository extends \Doctrine\ORM\EntityRepository
{
}
